# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: system
        entry: bash -c 'cd ./frontend && npm run lint:fix && npm run format'
        files: \.(js|jsx|ts|tsx|astro)$
        types: [file]


  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: bash -c 'cd ./backend  && uv run ruff check --fix'
      - id: ruff-format
        name: ruff-format
        language: system
        entry: bash -c 'cd ./backend  && uv run ruff format'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'cd ./backend  && uv run mypy src/ tests/ --config-file=mypy.ini'
        types_or: [python, pyi]
        language: system
        require_serial: true
