repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.0  # Use the latest version
    hooks:
    -   id: ruff
        name: ruff (backend)
        files: ^backend/
        args: [ --fix ]  # Added --fix option
    -   id: ruff-format
        name: ruff-format (backend)
        files: ^backend/

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: package-lock.json$
    -   id: check-merge-conflict

-   repo: local
    hooks:
    -   id: eslint
        name: eslint (frontend)
        entry: bash -c 'cd frontend && npm run lint:fix'
        language: system
        files: ^frontend/
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        pass_filenames: false
