version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres

  subscriber:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: subscriber
    env_file:
      - .env
    depends_on:
      - api

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: budget_buddy
      POSTGRES_PASSWORD: budget_buddy
      POSTGRES_DB: budget_buddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
