version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - API_URL=http://nginx/api
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend

  subscriber:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: subscriber
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  celeryworker:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: celeryworker
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - redis
    ports:
      - "5555:5555"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: budget_buddy
      POSTGRES_PASSWORD: budget_buddy
      POSTGRES_DB: budget_buddy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "THISISASECURECOOKIESTRING1234567890"
      RABBITMQ_LOAD_DEFINITIONS: "/etc/rabbitmq/definitions.json"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:
