version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped

  subscriber:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: subscriber
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    restart: unless-stopped
    depends_on:
      - api
# Production deployment example (uncomment when needed)
#
# services:
#   api-prod:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#       target: production
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     environment:
#       - PYTHONPATH=/app/src
#     restart: unless-stopped
#
#   subscriber-prod:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#       target: subscriber
#     env_file:
#       - .env
#     environment:
#       - PYTHONPATH=/app/src
#     restart: unless-stopped
#     depends_on:
#       - api-prod
