"""Add user table

Revision ID: 32b195585038
Revises: fe4ecb21022d
Create Date: 2025-05-08 18:24:49.125940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32b195585038"
down_revision: Union[str, None] = "fe4ecb21022d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_foreign_key(None, "budgets", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "categories", "users", ["user_id"], ["id"])
    op.create_foreign_key(
        None, "category_statistics_records", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(None, "statistics_records", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "transactions", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_constraint(None, "statistics_records", type_="foreignkey")
    op.drop_constraint(None, "category_statistics_records", type_="foreignkey")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_constraint(None, "budgets", type_="foreignkey")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
