"""Change date to datetime

Revision ID: ab7c9efa7031
Revises: c82c05d0c154
Create Date: 2025-04-27 01:10:34.752130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab7c9efa7031"
down_revision: Union[str, None] = "c82c05d0c154"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "budgets",
        "start_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "end_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "deactivation_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "budgets",
        "created_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "updated_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "categories",
        "created_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "categories",
        "updated_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "category_statistics_records",
        "created_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "statistics_records",
        "creation_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "statistics_records",
        "created_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "occurred_date",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "updated_at",
        existing_type=sa.DATE(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "transactions",
        "occurred_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "statistics_records",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "statistics_records",
        "creation_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "category_statistics_records",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "categories",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "categories",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "updated_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("CURRENT_DATE"),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "deactivation_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column(
        "budgets",
        "end_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    op.alter_column(
        "budgets",
        "start_date",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
