"""Associate stats record to transaction

Revision ID: fe4ecb21022d
Revises: e625dabd8f85
Create Date: 2025-05-06 01:15:37.947134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe4ecb21022d"
down_revision: Union[str, None] = "e625dabd8f85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statistics_records", sa.Column("transaction_id", sa.UUID(), nullable=True)
    )
    op.create_index(
        op.f("ix_statistics_records_transaction_id"),
        "statistics_records",
        ["transaction_id"],
        unique=True,
    )
    op.create_foreign_key(
        None,
        "statistics_records",
        "transactions",
        ["transaction_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "statistics_records", type_="foreignkey")
    op.drop_index(
        op.f("ix_statistics_records_transaction_id"), table_name="statistics_records"
    )
    op.drop_column("statistics_records", "transaction_id")
    # ### end Alembic commands ###
