"""budget schema

Revision ID: a7baec8a5b38
Revises: 
Create Date: 2023-12-15 00:11:27.823985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7baec8a5b38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'budgets', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'expenses', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'budgets', type_='unique')
    # ### end Alembic commands ###
